# Generated by Django 3.2.8 on 2021-10-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='basicPay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
