# Generated by Django 3.2.8 on 2021-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0002_alter_userprofile_basicpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default='0000000', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default='0000000', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jobNumber',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
